[package]
name = "textwrap"
version = "0.1.0"

[dependencies]
unicodeWidth = { git = "https://github.com/mcdearman/meadow-unicode-width", version = "0.1.0" }
unicodeLinebreak = { git = "https://github.com/mcdearman/meadow-unicode-linebreak", version = "0.1.0" }
