[package]
name = "textwrap"
version = "0.1.0"

[dependencies]
unicodeWidth = { git = "https://github.com/mcdearman/meadow-unicode-width" }
unicodeLinebreak = { git = "https://github.com/mcdearman/meadow-unicode-linebreak" }
